Some updates on "latest-changes"
osmlab/awesome-openstreetmap pull request #132
Opened 2022-10-25 03:11 UTC by rene78

- Moved latest-changes to "Changeset Tools"
- Updated description
- Changed repository tyrasd --> rene78 (more up-to-date)

2022-10-28 15:48 UTC, Unkn0wnCat requested changes
Looking good already. I'm on board with switching to your fork as it seems you were the only one actively contributing to the old version anyways and the original version seems to be unmaintained.

Please fix the sorting as described in the attached comment, and I'm happy to merge!

2022-10-28 15:48 UTC, Unkn0wnCat commented on README.md
> +* [latest-changes](https://rene78.github.io/latest-changes/#2/15.0/-15.0) - Visualize latest OSM changesets within a certain geographic boundary. Includes simple vandalism checker. ([Source Code](htt
I agree with the recategorization, but please move this to the bottom of the category as the categories are supposed to be sorted by date added and adding in the middle (even if just for a move) would kinda undermine that 😛

2022-10-29 15:10 UTC, rene78 commented
Thanks for the feedback! Makes sense. I have just moved it to the end of the list.

2022-10-29 18:16 UTC, Unkn0wnCat approved these changes

2022-10-29 18:17 UTC, merged

2022-10-29 18:17 UTC, Unkn0wnCat commented
Looking good! Thanks for helping with keeping this list up to date 🥇