Added project 'Arnis'
osmlab/awesome-openstreetmap pull request #140
Opened 2023-06-12 12:53 UTC by louis-e

Arnis is a Python project using OSM to generate cities from real life in Minecraft - experimental, but might be interesting enough to be added to the list :)

2023-06-12 18:46 UTC, mnalis approved these changes

2023-06-15 22:12 UTC, Unkn0wnCat requested changes
Hey @louis-e, thanks for your contribution. It already looks great, although I have one minor change I need you to apply before I can merge it. (See attached comment)

It seems the automatic linter has gone a bit haywire, so don't mind the failed action on the PR - This is not related to your PR and I'm looking into fixing it!

2023-06-15 22:12 UTC, Unkn0wnCat commented on README.md
> +* [Arnis](https://github.com/louis-e/arnis) - Generate cities from real life in Minecraft using Python. ([Source Code](https://github.com/louis-e/arnis))
For projects with only a GitHub link we omit the Source Code link, as duplicated links are bad practise.

```suggestion
* [Arnis](https://github.com/louis-e/arnis) - Generate cities from real life in Minecraft using Python.
```

2023-06-16 14:53 UTC, louis-e commented
Alright, thanks for the notice! I also removed the unnecessary part in the previous line (PraxisMapper).

2023-06-16 15:12 UTC, merged

2023-06-16 15:14 UTC, Unkn0wnCat commented
Great! Thanks for the addition (and the fix of the line above 😄).

Your project is really awesome and will fit right in on the list 🎉