Add Famxplor web map
osmlab/awesome-openstreetmap pull request #156
Opened 2024-09-04 13:49 UTC by alt250

World map featuring family travel blog posts

2024-09-04 13:58 UTC, mtmail commented
Looking at the map requires a "login or register with google" and later "Free to try during 30 days"

2024-09-04 14:10 UTC, alt250 commented
Thanks for reviewing this PR @mtmail !

> Looking at the map requires a "login or register with google" and later "Free to try during 30 days"

Yes. Creating an account is free. 
Sorry is this is not allowed in this list, feel free to close this PR. 

Here is what the map looks like FYI:
![Screenshot from 2024-09-04 16-09-05](https://github.com/user-attachments/assets/a9bd2238-19e7-4e69-a863-fd3e5a94c021)

2024-09-06 10:12 UTC, alt250 commented
Another screenshot with more context (family travel activities):

![image](https://github.com/user-attachments/assets/4a250491-d88f-4165-8453-ecca03986987)

Thanks!

2024-09-07 13:53 UTC, Unkn0wnCat requested changes
Hey @alt250,

thanks for your contribution, however I have to agree with @mtmail. Awesome-Lists are normally meant to showcase FOSS-projects, and whilst we do have a few non-open-source tools in our lists, all of them can be used for free.

I therefore see a problem with adding Famxplor to the main list. However we may still be able to work with this by adding a secondary list. Just as we have `UNMAINTAINED.md` for unmaintained projects, we could have a `NONFREE.md`.

My suggestion is for you to remove your change to the `README.md` and create a `NONFREE.md` with the following content instead: 

```md
# Non-Free Projects

The projects listed here are cool too, but can only be used against payment and don't publish their sources. 
These commercial products are seperated from the main list to keep the main focus of the list on FOSS-projects.

## Contents

* [Maps](#maps)
  * [Web Maps](#web-maps)

## Maps

### Web Maps

* [Famxplor](https://famxplor.com/) - World map featuring travel with kids blog posts. Find activities for your family vacations worldwide.
```

Let me know what you think!

2024-09-09 14:23 UTC, alt250 commented
Hey @Unkn0wnCat ,
Thanks for your insightful comment!

I think that adding a `NONFREE.md` list is a good idea. It will make the distinction between free and non-free explicit.

It just happened that in the meantime, I decided to make [Famxplor](https://www.famxplor.com/) free!
It is based on several free projects (like OSM) and content sources, so it makes more sense like this.

Famxplor being free now, it can stay in the `README.md` if that's OK for you.

2024-09-09 19:45 UTC, mnalis commented
> Famxplor is now free but still closed-source, so should I add it to `NONFREE.md` as you suggested?

As it is not [FOSS](https://en.wikipedia.org/wiki/FOSS), I think adding it to `NONFREE.md` would be appropriate.

2024-09-11 13:48 UTC, alt250 commented
Hey @Unkn0wnCat,
I created `NONFREE.md` and added Famxplor to it.
Note that I slightly modified the intro text of the non-free page.

2024-09-11 14:16 UTC, mnalis requested changes

2024-09-13 13:32 UTC, alt250 commented
@mnalis Thanks for clarifying the text!
I also added "gratis, closed-source" after Famxplor as you suggested

2024-09-13 14:03 UTC, mtmail commented
I still think the website not OSM related enough and I don’t see it promoting OSM. Closed data is displayed on a base map behind a login, OSM attribution behind a tiny (i) on the bottom right of the map. 100.000s websites use a OSM basemap similarly. It’s one of five PRs to various awesome-* by the owner.
Of course I encourage the repo maintainers to add what they see fit.

2024-09-13 14:54 UTC, alt250 commented
@mtmail Thank you for the feedback! I appreciate your perspective on the OSM relevance.

I'd like to clarify a few points:
* The map on Famxplor features publicly available data displayed on a world map, which is powered by OSM.
* Account creation on Famxplor is free, and the product itself is now entirely free to use.
* The "(i)" icon in the bottom right is part of the MapLibre framework ([documentation](https://maplibre.org/maplibre-gl-js/docs/API/classes/AttributionControl/)). By default, it displays attributions and auto-hides when the map is moved. I've attached a screenshot for reference:

![image](https://github.com/user-attachments/assets/dffc0e3f-ea3a-4351-8384-d604483f7d78)

While Famxplor does use OSM as its core mapping service, I understand the importance of making that more apparent. To address this, I've added a "Built with OpenStreetMap" link at the bottom of the map page. This is visible in the screenshot above.

Regarding the multiple PRs to awesome-* projects, I submitted them in the hopes of contributing to lists where I thought the project might be relevant. However, I fully respect the maintainers' decision to include what they deem appropriate.

Thank you for your understanding and encouragement!

2024-09-13 16:59 UTC, mnalis commented
>  Of course I encourage the repo maintainers to add what they see fit.

While I helped trying to format this PR to be more usable **_if_** it were to be accepted, I absolutely agree that the maintainer should make a **decision about where they'd want to take this project** (and **document it**). 

I.e., besides project having to be "awesome" (which is obviously highly subjective, and always subject to maintainer's final decision), should:

1. non-FOSS projects be accepted in the list (never / always / only in ***very exceptional*** circumstances) ?
2. walled-garden (i.e. requiring account to access) projects be accepted in the list (never / always / only those requiring OSM login  / only if creating account is gratis and project is non-commercial / only if creating account is gratis (but upsell is fine) / only in very exceptional circumstances) ?

<details>

<summary>my personal preferences would be:</summary>

1. only in very exceptional circumstances (e.g. hugely popular HDYC) 
2. only those requiring OSM login (but might accept _"only if creating account is gratis and project is non-commercial"_ too)

</details>

2024-09-18 08:33 UTC, alt250 commented
> I.e., besides project having to be "awesome" (which is obviously highly subjective, and always subject to maintainer's final decision), should:
> 
> non-FOSS projects be accepted in the list (never / always / only in very exceptional circumstances) ?
> walled-garden (i.e. requiring account to access) projects be accepted in the list (never / always / only those requiring OSM login / only if creating account is gratis and project is non-commercial / only if creating account is gratis (but upsell is fine) / only in very exceptional circumstances) ?

I fully understand that the submission of this project triggered these questions. 
However, would [discussions](https://github.com/osmlab/awesome-openstreetmap/discussions) be a more appropriate place to discuss such matters?

2024-09-24 16:26 UTC, Unkn0wnCat commented
Heyo everyone, 

sorry I've been a bit absent from this conversation. Thanks for all the input to this conversation from everyone!

As mentioned by @alt250 we should move the discussion about adding non-free stuff to the Discussions tab. I've just created a topic there with my view of the problem: https://github.com/osmlab/awesome-openstreetmap/discussions/158

Let's put this PR on ice for the length of the discussion.

I encourage everyone who contibuted to this conversation to take part in the discussion: 
@alt250 @mnalis @mtmail

2026-03-11 15:07 UTC, closed without merging